<?php
/**
 * Created by PhpStorm.
 * User: fannyperret
 * Date: 02/10/2017
 * Time: 10:24
 */
namespace  Wcs;

class Desktop extends Computer
{
    private $Boxtype;

    public function __construct($model, $weight, $proc = "")
    {
        parent::__construct($model, $proc);
        $this->setBoxtype($weight);

    }

    /**
     * @return mixed
     */
    public function getBoxtype()
    {
        return $this->Boxtype;
    }

    /**
     * @param mixed $Boxtype
     */
    public function setBoxtype($Boxtype)
    {
        $this->Boxtype = $Boxtype;
        return $this;
    }

    public function display()
    {
        parent::display(); // TODO: Change the autogenerated stub
        echo "Boitier : " . $this->getBoxtype() . PHP_EOL;
    }

    public function getSpeed()
    {
        // TODO: Implement getSpeed() method.
    }
}