<?php
/**
 * Created by PhpStorm.
 * User: fannyperret
 * Date: 02/10/2017
 * Time: 09:57
 */
namespace Wcs;

class Laptop extends Computer
{
    private $weight;

    public function __construct($model, $weight, $proc = "")
{
    parent::__construct($model, $proc);
    $this->setWeight($weight);

}

    /**
     * @return mixed
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * @param mixed $weight
     */
    public function setWeight($weight)
    {
        $this->weight = $weight;
        return $this;
    }

    public function display()
    {
        parent::display(); // TODO: Change the autogenerated stub
        echo "Poids : " . $this->getWeight() . PHP_EOL;
    }

    public function getSpeed()
    {
        // TODO: Implement getSpeed() method.
    }
}